name: Test and Package

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  create:
    tags:
      "*"
      
jobs:  

  test:
    runs-on: ubuntu-22.04
    
    steps:
    
    - name: Setup Python
      uses: actions/setup-python@v4.7.0
      with:
        python-version: "3.10"

    - uses: actions/checkout@v3
    
    - name: Install 
      run: |
        pip install -e ".[dev]"
    
    - name: Test
      run: |
        pytest      
    
    
